import './globals.css'
import Header from "@/app/components/Header";


import { Mulish } from 'next/font/google'
import Footer from "@/app/components/Footer";

const mulish = Mulish({
  weight: ['300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'],
})


export const metadata = {
  title: 'CS Society', description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (<html lang="en">
    <body className={mulish.className}>
      <Header />
      {children}
      <Footer />
    </body>
  </html>)
}